apiVersion: v1
kind: Pod
metadata:
  name: html-app
  labels:
    app: html-app
spec:
  containers:
    - name: html-app
      image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
      command: ["python3"]
      args: ["-m", "http.server", "8080"]
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      securityContext:
        runAsUser: 1001
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
  volumes:
    - name: html-volume
      configMap:
        name: html-index
